version: "3"
services:
  psql:
    image: postgres:latest
    volumes:
      - "./psql-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=ttrss
      - POSTGRES_USER=ttrss
      - POSTGRES_PASSWORD=ttrss
    ports:
      - "127.0.0.1:5432:5432"

  ttrss:
    image: ewgb/ttrss:postgres
    ports:
      - "80:80"
    depends_on:
      - psql
    environment:
      - TTRSS_DB_TYPE=pgsql
      - TTRSS_DB_HOST=psql
      - TTRSS_DB_PORT=5432
      - TTRSS_DB_USER=ttrss
      - TTRSS_DB_NAME=ttrss
      - TTRSS_DB_PASS=ttrss
      - TTRSS_SELF_URL_PATH=http://reader.belzmann.de/
      - TTRSS_FEED_CRYPT_KEY=@HCcMWQ+U_RnSI-HZO76pUJr
      - VIRTUAL_HOST=reader.belzmann.de
      - VIRTUAL_PORT=54321
    volumes:
      - "ttrss_cache:/app/cache"
      - "./feed-icons:/app/feed-icons"
      - "./plugins.local:/app/plugins.local"

volumes:
  ttrss_cache:
    driver: local
