---

version: '2'
services:
  pgsql:
    image: postgres
    environment:
      - POSTGRES_DB=ttrss
      - POSTGRES_USER=ttrss
      - POSTGRES_PASSWORD=ttrsspassword

  ttrss:
    build: .
    image: ewgb/ttrss:postgres
    ports:
      - "8080:80"
    links:
      - pgsql
    environment:
      - TTRSS_DB_HOST=pgsql
      - TTRSS_DB_USER=ttrss
      - TTRSS_DB_NAME=ttrss
      - TTRSS_DB_PASS=ttrsspassword
      - TTRSS_FEED_CRYPT_KEY=@HCcMWQ+U_RnSI-HZO76pUJr
    volumes:
      - "ttrss_cache:/app/cache"
      - "ttrss_icons:/app/feeds-icons"

volumes:
  ttrss_cache:
    driver: local
  ttrss_icons:
    driver: local
