---

web:
  build: .
  ports:
    - "8080:80"
  links:
    - mysql
  environment:
    - TTRSS_DB_USER=ttrss
    - TTRSS_DB_NAME=ttrss
    - TTRSS_DB_PASS=ttrsspassword
    - TTRSS_FEED_CRYPT_KEY=@HCcMWQ+U_RnSI-HZO76pUJr
mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_DATABASE=ttrss
    - MYSQL_USER=ttrss
    - MYSQL_PASSWORD=ttrsspassword
